version: '2'
services:
    nginx:
        build:
            context: ./
            dockerfile: docker/nginx.docker
        volumes:
          - ./:/var/www
        ports:
            - 80:80
        links:
            - php-fpm
    php-fpm:
        build:
            context: ./
            dockerfile: docker/php-fpm.docker
        volumes:
            - ./:/var/www
        links:
            - mysql
            - redis
    php-cli:
        build:
            context: ./
            dockerfile: docker/php-cli.docker
        volumes:
            - ./:/var/www
        links:
            - mysql
            - redis
        tty: true
    mysql:
        image: mysql:5.7
        environment:
            - "MYSQL_ROOT_PASSWORD=root"
            - "MYSQL_USER=app"
            - "MYSQL_PASSWORD=root"
        ports:
            - "3306:3306"
    redis:
        image: redis:3.0
        ports:
            - 63791:6379
    node:
        image: node:8.6-alpine
        volumes:
            - ./:/var/www
        working_dir: /var/www
        tty: true

